### ISSUE TITLE
Delete only selected cached images

### ISSUE THREAD

**Issue by SonOfCrypto** [junaidbhura/fly-dynamic-image-resizer#13]
Hi Junaid!

Is it possible to delete selected images from the cache? My site has lots of images and I do not want to delete the whole cache, if I upload a new version of an image by using this plugin https://wordpress.org/plugins/enable-media-replace/

Thx Jan

**Comment by junaidbhura** [comment]
Hey @janwagner have you tried deleting it from under "Media Library"? You can click on "Delete Fly Images" next to the image:
https://github.com/junaidbhura/fly-dynamic-image-resizer/blob/master/screenshot-1.png

You can also do it via CLI:
https://github.com/junaidbhura/fly-dynamic-image-resizer/wiki/WP-CLI

**Comment by SonOfCrypto** [comment]
thank you @junaidbhura! that is exactly what I was looking for.
