### ISSUE TITLE
Change to must use plugins

### ISSUE THREAD

**Issue by mr660** [junaidbhura/fly-dynamic-image-resizer#24]
Hey! 
First off great plugin! It's sad it's not so popular when Wp image sizes totally sucks.

I'm using a composer and i think You should change plugin to must use plugins. Need only little change to make main file outside of plugin folder. [Because of this](https://wordpress.stackexchange.com/questions/26337/plugins-in-mu-plugins-folder-are-not-loaded)

**Comment by junaidbhura** [comment]
Hi @mr660 thanks for the issue!

This is currently not planned for this plugin.

If you're using Composer, you can make this plugin an `mu-plugin` by defining it as such. Something like:

`"wp-content/mu-plugins/{$name}/": ["type:wordpress-muplugin", "wpackagist-plugin/fly-dynamic-image-resizer"],`

And using an MU plugin loader. Something like this:
https://github.com/junaidbhura/wp-project-base/blob/master/web/wp-content/mu-plugins/loader.php
