### ISSUE TITLE
Force Image Crop 

### ISSUE THREAD

**Issue by hlaporthein** [junaidbhura/fly-dynamic-image-resizer#29]
Is there any method that could make force image crop? 
For example, if I use original image ( 250x200 )  and I would to get (350x300) size. Even image could be blur because force image crop, it could be more useful in some places.

**Comment by junaidbhura** [comment]
Hey @hlaporthein thanks for this issue!

This plugin uses core WordPress functions to do the resizing under the hood. Unfortunately, there is currently no support for this, and it doesn’t look like they’re going to add support in the foreseeable future.

I’ll make a note of this for future releases, though.

Thanks again!
