### ISSUE TITLE
crop center position

### ISSUE THREAD

**Issue by jmarceli** [junaidbhura/fly-dynamic-image-resizer#3]
Is it possible to set crop center position like in default WP method (https://developer.wordpress.org/reference/functions/add_image_size/ )?

**Comment by junaidbhura** [comment]
@jmarceli That's a great feature to have, and might be part of a future release. But as of now, this is not currently supported or planned.

**Comment by junaidbhura** [comment]
@jmarceli Just to update you, the new version of this plugin now supports this:

https://github.com/junaidbhura/fly-dynamic-image-resizer/releases/tag/1.0.5

**Comment by jmarceli** [comment]
Thanks for the info it is a very useful feature.
