### ISSUE TITLE
Add filter to modify image path

### ISSUE THREAD

**Issue by joppuyo** [junaidbhura/fly-dynamic-image-resizer#33]
My use case is that I have a plugin that optimizes images but it creates a backup image before optimizing the image.

When creating a fly image I would like to use this backup instead of the optimized image so it doesn't get optimized twice thus ensuring better quality.

I would like to add a filter to this plugin you can use to change the image path that is used so the plugin can check if a backup exists and return path to the backup instead.

I have a pull request for this, I will attach it in a second.

**Comment by joppuyo** [comment]
Created pull request https://github.com/junaidbhura/fly-dynamic-image-resizer/pull/34

**Comment by junaidbhura** [comment]
Thanks @joppuyo let me take a look at this at length and get back to you!

**Comment by junaidbhura** [comment]
@joppuyo I've merged the PR, thanks for your contribution! This will be part of the next plugin release!
