### ISSUE TITLE
Don't work when use MAMP Pro and local development use remote Images

### ISSUE THREAD

**Issue by supriome** [junaidbhura/fly-dynamic-image-resizer#35]
When use MAMP Pro for local Wordpress development, function fly_get_attachment_image_src() can't get the right url and return undefined.

Link:[MAMP PRO FOR LOCAL WORDPRESS DEVELOPMENT](https://anthonyskelton.com/2017/mamp-pro-local-wordpress-development/)

**Comment by junaidbhura** [comment]
Hi @supriome this plugin requires images to be locally available. It does not work with remote images, sorry about that!
