### ISSUE TITLE
Support for src/sizes?

### ISSUE THREAD

**Issue by gglnx** [junaidbhura/fly-dynamic-image-resizer#36]
First: Thanks for your plugin!

Do you plan to add companions for `wp_get_attachment_image_srcset` and `wp_get_attachment_image_sizes`?

**Comment by junaidbhura** [comment]
Thanks @gglnx , I'm glad you find it useful. I'm currently contemplating hooking into core WordPress function #26 . You can keep a track of this on that issue there.

I'll close this issue right now, but please feel free to continue this discussion there.
