### ISSUE TITLE
There is no images in fly-images folder

### ISSUE THREAD

**Issue by kaito-th** [junaidbhura/fly-dynamic-image-resizer#52]
There is no images in fly-images folder
and I want to ask if I deleted the default resized images this plugin can regenerate them or not ?

**Comment by junaidbhura** [comment]
Hi there,
Yes - it should be able to regenerate the images if the images are deleted. In fact, there is an option for this in the back-end.

**Comment by kaito-th** [comment]
in ( Tools > Fly Images ) has only "Fly Images Directory" and "Delete Cached Images". There is no regenerate option

**Comment by junaidbhura** [comment]
Images are generated "on the fly" - that is - when the user first visits the page that the image is on. It is created at that point and is cached.
