### ISSUE TITLE
Image optimiser compatability

### ISSUE THREAD

**Issue by jakewhiteley** [junaidbhura/fly-dynamic-image-resizer#6]
This isn't an issue as such; More of an enhancement really.

Has this plugin been tested with image optimisers such as  [ewww](https://en-gb.wordpress.org/plugins/ewww-image-optimizer/)?

If not are there any plans to add the needed hooks etc in the future so third party image optimisers will correctly run when a new image is generated?

**Comment by junaidbhura** [comment]
Hi there, thanks for bringing this up. There was a hook added for this very reason in verson 1.0.5:
https://github.com/junaidbhura/fly-dynamic-image-resizer/releases/tag/1.0.5

There are no plans to support third-party image optimization plugins at the moment, but you can use that hook to easily integrate with them.

If you have a pull request which hooks up with Kraken or Ewww, I'd be happy to take a look at it!
