### ISSUE TITLE
Does not work on WordPress 4.8.1

### ISSUE THREAD

**Issue by mikeboothdesign** [junaidbhura/fly-dynamic-image-resizer#7]
All functions seem to return an empty array. Example: the following returns an empty array, even if the image with ID 81 exists in the media library.

`echo fly_get_attachment_image_src( 81, 'home_page_square', array( 500, 500 ), true );`

**Comment by mikeboothdesign** [comment]
Sorry, user error. Questionable WordPress database issue.

**Comment by junaidbhura** [comment]
Haha @mikeboothdesign no worries, it happens :)
