### ISSUE TITLE
Q; upscale

### ISSUE THREAD

**Issue by basz** [junaidbhura/fly-dynamic-image-resizer#8]
I don't think your plugin supports upscaling? But perhaps I just can't find it...

Suppose the source image is smaller then a defined image size, will it create an image with the source placed on the larger canvas?

further a great plugin, thanks

**Comment by junaidbhura** [comment]
Hey @basz the plugin currently does not support that. But I've made a note of it for the future.

Cheers!

**Comment by nicooprat** [comment]
Hi, any plan to add this feature? Can't find the note you're talking about.

**Comment by junaidbhura** [comment]
Hey @nicooprat it was an internal note 😊

It's still not on the roadmap, sorry!

**Comment by krishaamer** [comment]
Hi, also badly need this. Can we maybe use this solution in Fly also?  http://alxmedia.se/code/2013/10/thumbnail-upscale-correct-crop-in-wordpress/

@junaidbhura

**Comment by junaidbhura** [comment]
Hey @krishaamer unfortunately, there are currently no plans to support image upscaling. But I'd be open to seeing a pull request with some ideas to see if it would be a good fit for this plugin?
